// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Read() {
  return window['go']['configuration']['ReadWriter']['Read']();
}

export function Write(arg1) {
  return window['go']['configuration']['ReadWriter']['Write'](arg1);
}
