// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configuration} from '../models';

export function Read():Promise<configuration.Configuration>;

export function Write(arg1:configuration.Configuration):Promise<void>;
