// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configuration} from '../models';

export function Get():Promise<configuration.Configuration>;

export function Set(arg1:configuration.Configuration):Promise<void>;
