// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function Create(arg1:frontend.ProjectDto):Promise<frontend.ProjectDto>;

export function Delete(arg1:frontend.ProjectDto):Promise<void>;

export function GetAll():Promise<Array<frontend.ProjectDto>>;

export function Update(arg1:frontend.ProjectDto):Promise<frontend.ProjectDto>;
