// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['frontend']['Projects']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['frontend']['Projects']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['frontend']['Projects']['GetAll']();
}

export function Update(arg1) {
  return window['go']['frontend']['Projects']['Update'](arg1);
}
