// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['frontend']['Websocket']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['frontend']['Websocket']['Disconnect'](arg1);
}

export function Send(arg1, arg2) {
  return window['go']['frontend']['Websocket']['Send'](arg1, arg2);
}
