// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function Connect(arg1:frontend.WebsocketRequestDto):Promise<frontend.WebsocketStateDto>;

export function Disconnect(arg1:frontend.WebsocketRequestDto):Promise<frontend.WebsocketStateDto>;

export function Send(arg1:frontend.WebsocketRequestDto,arg2:string):Promise<frontend.WebsocketStateDto>;
